Controllers/GenCodeController.cs
using AutoGenCode.Data;
using AutoGenCode.Models;
using AutoGenCode.Repository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGenCode.Controllers
{
    public class GenCodeController : Controller
    {
        private static Random random = new Random();
        private readonly TagRepository _tagRepository = null;
        private readonly RegionRepository _regionRepository = null;
        private readonly GenUIRepository _genUIRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public GenCodeController(
            TagRepository tagRepository,
            RegionRepository regionRepository,
            GenUIRepository genUIRepository,
            IWebHostEnvironment webHostEnvironment
        )
        {
            _tagRepository = tagRepository;
            _regionRepository = regionRepository;
            _genUIRepository = genUIRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GenRegion(bool isSuccess = false, int regionId = 0, string regionName = "")
        {
            ViewBag.IsSuccess = isSuccess;
            ViewBag.RegionId = regionId;
            ViewBag.RegionName = regionName;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GenRegion(RegionModel region)
        {
            if (ModelState.IsValid)
            {
                int id = await _regionRepository.AddNewRegion(region);
                if (id > 0)
                {
                    var dateTime = DateTime.UtcNow.GetHashCode().ToString();
                    string readFilePath = "wwwroot\\code\\template.html";
                    string fileName = CreateNewRegionFile(readFilePath, region, dateTime);
                    return RedirectToAction(nameof(GenRegion), new { isSuccess = true, regionId = id, regionName = fileName });
                }
            }
            return View();
        }

        public IActionResult GenCode(bool isSuccess = false, int tagId = 0, string tagName = "")
        {
            ViewBag.IsSuccess = isSuccess;
            ViewBag.TagId = tagId;
            ViewBag.TagName = tagName;
            return View();
        }

        [HttpPost]
        public IActionResult GenCode(int Id)
        {
                if (Id != 0)
                {
                    var tag = _tagRepository.GetTagById(Id).Result;
                    string readFilePath = "wwwroot\\code\\template.html";
                    string writeFilePath = CreateNewTagFile(readFilePath, tag);
                    return RedirectToAction(nameof(GenCode), new { isSuccess = true, tagId = Id, tagName = tag.TagName });
            }
            return View();
        }

        public FileResult DownloadFile(string fileName)
        {
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "code\\result\\") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, "application/octet-stream", fileName);
        }

        private string CreateNewTagFile(string readFilePath, TagModel tag)
        {
            string fileName = tag.TagName;
            string writeFilePath = "wwwroot\\code\\result\\" + fileName + "Tag.html";
            string content = "<" + fileName + ">" + "<" + fileName + "/>";
            try
            {
                StreamReader sr = new StreamReader(readFilePath);
                string path = Path.Combine(_webHostEnvironment.WebRootPath, writeFilePath);
                StreamWriter sw = new StreamWriter(writeFilePath);
                string line = sr.ReadLine();
                while (line != null)
                {
                    if (line.Length == 0)
                    {
                        sw.WriteLine(content);
                    }
                    else
                    {
                        sw.WriteLine(line);
                    }
                    line = sr.ReadLine();
                }
                sr.Close();
                sw.Close();
                return writeFilePath;
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.Message);
            }
            finally
            {
                Console.WriteLine("Executing finally block.");
            }
            return null;
        }

        private string CreateNewRegionFile(string readFilePath, RegionModel region, string dateTime)
        {
            var tag = _tagRepository.GetTagById(region.TagId).Result;
            string tagName = tag.TagName;
            string fileName = tagName + "_" + dateTime + ".html";
            string writeFilePath = "wwwroot\\code\\result\\" + fileName;

            string attr = "<" + tagName +
                                    " height=\"" + region.Height + "\"" +
                                    " width=\"" + region.Width + "\"";
            if (tag.HasEndTag) { 
                attr += ">" + tagName + "</" + tagName + ">";
            }
            else
            {
                attr += "/>";
            }
            
            try
            {
                StreamReader sr = new StreamReader(readFilePath);
                string path = Path.Combine(_webHostEnvironment.WebRootPath, writeFilePath);
                StreamWriter sw = new StreamWriter(writeFilePath);
                string line = sr.ReadLine();
                while (line != null)
                {
                    if (line.Length == 0)
                    {
                        sw.WriteLine(attr);
                    }
                    else
                    {
                        sw.WriteLine(line);
                    }
                    line = sr.ReadLine();
                }
                sr.Close();
                sw.Close();
                return fileName;
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.Message);
            }
            finally
            {
                Console.WriteLine("Executing finally block.");
            }
            return null;
        }
    }
}

Views/GenCode/CreateTextFile.cshtml
@{
    ViewBag.Title = "Create Text File";
}

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td><label>Enter Text :</label></td>
            <td>@Html.TextArea("message", new { cols = 50, rows = 8 })</td>
        </tr>
        <tr>
            <td></td>
            <td><input id="Submit1" type="submit" value="Ctreate Text File" /></td>
        </tr>
    </table>
}

Views/GenCode/GenCode.cshtml
@inject AutoGenCode.Repository.TagRepository _elementRepo;
@model TagModel;
@{
    ViewData["Title"] = "Gencode";
}
<h3 class="display-4">Gencode</h3>
@if (ViewBag.IsSuccess != null && ViewBag.IsSuccess == true)
{
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Gen code success</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    @Html.ActionLink("Download", "DownloadFile", "GenCode", new{fileName = @ViewBag.TagName + "Element.html"})
</div>
}

<form method="POST" asp-action="GenCode">
    <div class="form-group">
        <label asp-for="TagId"></label>
        <select asp-for="TagId" class="form-control" asp-items="(await _elementRepo.GetTags()).Select(x=> new SelectListItem() {Text = x.TagName, Value=x.TagId.ToString()})">
            <option value="">Please choose Item</option>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Gencode" class="btn btn-primary" />
    </div>
</form>
© 2021 GitHub, Inc.

Views/GenCode/GenRegion.cshtml
@inject AutoGenCode.Repository.TagRepository _tagRepo;

@model RegionModel;

@{
    ViewData["Title"] = "Gencode";
}

<h3 class="display-4">GenRegion</h3>
@if (ViewBag.IsSuccess != null && ViewBag.IsSuccess == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Gen code success</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.ActionLink("Download", "DownloadFile", "GenCode", new { fileName = ViewBag.RegionName })
    </div>
}

<form method="POST" asp-action="GenRegion">
    <div class="form-group">
        <label asp-for="TagId"></label>
        <select asp-for="TagId" class="form-control"
                asp-items="(await _tagRepo.GetTags())
                .Select(x=> new SelectListItem() {Text = x.TagName, Value=x.TagId.ToString()})">
            <option value="">Please choose Item</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Width"></label>
        <input asp-for="Width" type="number" placeholder="Width" step="0.01" />
    </div>
    <div class="form-group">
        <label asp-for="Height"></label>
        <input asp-for="Height" type="number" placeholder="Height" step="0.01" />
    </div>
    <div class="form-group">
        <label asp-for="LeftPos"></label>
        <input asp-for="LeftPos" type="number" placeholder="LeftPos" step="0.01" />
    </div>
    <div class="form-group">
        <label asp-for="RightPos"></label>
        <input asp-for="RightPos" type="number" placeholder="RightPos" step="0.01" />
    </div>

    <div class="form-group">
        <input type="submit" value="GenRegion" class="btn btn-primary" />
    </div>
</form>
© 2021 GitHub, Inc.